#Logistic Regression Implementation

In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

#It will create the dataset in classification approach it will create independent feature it will able to create dependent feature in output we can say that how many outputs we want, It will create dataset in such a way that we don't even have to do Standardiztion.

In [42]:
#it will create Dataset
from sklearn.datasets import make_classification

In [43]:
#creating Dataset
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2)

In [44]:
X

array([[ 0.1918626 ,  1.02524062, -0.93178406, ..., -0.09319286,
        -0.99150023, -0.37188346],
       [-0.07419041,  0.79378217, -0.53515659, ..., -0.89433753,
        -1.46639952,  0.54759249],
       [ 0.31336837, -0.96130719,  0.98517336, ...,  1.55098169,
        -0.76332572, -0.276749  ],
       ...,
       [-0.42624904,  1.05302266, -1.35865639, ..., -1.70369845,
         1.25805591,  0.35483242],
       [ 0.77356093, -1.20173689, -0.77766083, ..., -1.05986334,
         1.07903323, -0.00976689],
       [-1.2455364 , -1.32063906,  1.07031794, ...,  1.61733207,
         0.18074181, -0.85684953]])

In [45]:
y

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,

In [46]:
#Converting X into Dataframe
df = pd.DataFrame(X)
df

0         1         2         3         4         5         6  \
0    0.191863  1.025241 -0.931784  1.645045 -1.438517  0.429206  1.191846   
1   -0.074190  0.793782 -0.535157 -0.995575  0.129071 -0.689470  0.846727   
2    0.313368 -0.961307  0.985173 -1.016829  2.053909 -0.925876  2.097345   
3    0.463211 -0.871569  0.401292 -0.672614 -0.531671 -0.341861 -0.135264   
4   -0.259023 -0.905126  0.400525 -0.792036  1.306828 -0.009408 -0.621060   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.382071  0.412238 -0.029966 -1.744826  1.283103 -1.364863  0.518088   
996 -0.211760  0.663205  1.241525  0.106281  1.244107  0.909600  0.151529   
997 -0.426249  1.053023 -1.358656  0.909705 -2.084076 -0.278211  1.076963   
998  0.773561 -1.201737 -0.777661  1.505689 -2.076754  0.034721  0.840327   
999 -1.245536 -1.320639  1.070318  1.256447  0.218223 -0.866193  0.111853   

            7         8         9  
0   -0.093193 -0.991500 -0.371883  
1   -0.894338 -1.466400  0.547592  
2    1.550982 -0.763326 -0.276749  
3   -1.397709 -0.981687  0.639141  
4    0.832408  0.781503 -0.088116  
..        ...       ...       ...  
995 -0.212292 -1.064168  0.499991  
996  1.708282  0.167906 -0.605590  
997 -1.703698  1.258056  0.354832  
998 -1.059863  1.079033 -0.009767  
999  1.617332  0.180742 -0.856850  

[1000 rows x 10 columns]

In [47]:
##Converting y into Dataframe
y_df = pd.DataFrame(y)
y_df

0
0    1
1    0
2    0
3    0
4    0
..  ..
995  0
996  0
997  0
998  1
999  1

[1000 rows x 1 columns]

##Train-Test-Split

In [48]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [49]:
X_train.shape,X_test.shape

((700, 10), (300, 10))

#Implementing Logistic Regression

In [50]:
from sklearn.linear_model import LogisticRegression
regression = LogisticRegression()
regression

LogisticRegression()

In [51]:
#model training
regression.fit(X_train,y_train)

LogisticRegression()

In [52]:
#predict new data
y_pred = regression.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

#Performance metrics in Logistic Regression

#Accuracy
#Confusion Matrix
#Precision
#Recall

In [53]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [54]:
score = accuracy_score(y_test,y_pred)
print(score)

0.94


In [55]:
confusion = confusion_matrix(y_test,y_pred)
print(confusion)
class_report = classification_report(y_test,y_pred)
print(class_report)

[[137  15]
 [  3 145]]
              precision    recall  f1-score   support

           0       0.98      0.90      0.94       152
           1       0.91      0.98      0.94       148

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300



#Hyperparameter Tunning and Cross-Validation


In [56]:
model = LogisticRegression()
model

LogisticRegression()

In [70]:
penalty = ['l1','l2','elastic_net']
c_values = [100,10,1.0,0.1,0.01]
solver = ['netwon_cg','lbfgs','liblinear','saga','sag']


In [71]:
#converting list data into key:value_pairs(Dict)
params = dict(penalty=penalty,C=c_values,solver=solver)
params

{'penalty': ['l1', 'l2', 'elastic_net'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['netwon_cg', 'lbfgs', 'liblinear', 'saga', 'sag']}

In [72]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

#For Hyperparameter we use **GirdSearch CV**

In [79]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elastic_net'],
                         'solver': ['netwon_cg', 'lbfgs', 'liblinear', 'saga',
                                    'sag']},
             scoring='accuracy')

In [80]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elastic_net'],
                         'solver': ['netwon_cg', 'lbfgs', 'liblinear', 'saga',
                                    'sag']},
             scoring='accuracy')

In [81]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
225 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
26 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elastic_net'],
                         'solver': ['netwon_cg', 'lbfgs', 'liblinear', 'saga',
                                    'sag']},
             scoring='accuracy')

In [82]:
grid.best_params_

{'C': 1.0, 'penalty': 'l1', 'solver': 'saga'}

In [83]:
grid.best_score_

0.9314285714285715

In [86]:
y_pred = grid.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [88]:
score = accuracy_score(y_test,y_pred)
print(score)
confusion = confusion_matrix(y_test,y_pred)
print(confusion)
class_report = classification_report(y_test,y_pred)
print(class_report)

0.9433333333333334
[[138  14]
 [  3 145]]
              precision    recall  f1-score   support

           0       0.98      0.91      0.94       152
           1       0.91      0.98      0.94       148

    accuracy                           0.94       300
   macro avg       0.95      0.94      0.94       300
weighted avg       0.95      0.94      0.94       300

