#Logistic Regression for multiclassification problem statement


In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


In [42]:
from sklearn.datasets import make_classification

In [43]:
X,y = make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3)

In [44]:
X

array([[ 9.26793578e-01, -1.11115674e+00,  8.24406535e-01, ...,
        -7.99539900e-01, -1.07476318e+00, -9.43902391e-01],
       [-1.69659251e+00, -4.92596988e-01,  1.76263033e+00, ...,
        -2.23450802e-01, -4.89258790e-01,  2.03607584e+00],
       [-4.07593659e-01, -1.94870317e-01,  4.24278155e-01, ...,
         1.60027304e-01,  4.21380292e-01, -5.87906562e-01],
       ...,
       [ 1.60792938e+00, -7.96752464e-01, -3.18217478e-02, ...,
         1.86622767e+00, -3.52904958e-04, -7.09395633e-01],
       [ 2.29812024e+00, -4.45846227e-01, -1.65763727e+00, ...,
        -2.96028920e-01, -9.03850984e-01, -6.34236032e-01],
       [ 5.70300848e-01, -1.76814775e+00,  9.33658986e-01, ...,
        -4.81403431e-01, -7.21238761e-01, -9.81176963e-01]])

In [45]:
y

array([2, 1, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1, 2,
       0, 2, 1, 1, 1, 0, 0, 2, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2,
       1, 2, 2, 2, 2, 0, 2, 1, 2, 1, 0, 2, 2, 2, 1, 0, 1, 1, 0, 2, 1, 2,
       2, 0, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 2, 0, 0, 2, 0, 1, 0, 2, 1, 1,
       0, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 0, 0, 1, 2, 0, 1, 1, 0, 1, 2,
       2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 2, 1, 0, 2, 2, 0, 0, 1, 1, 2, 1, 0,
       0, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 0, 1, 0, 0, 0, 2, 2,
       2, 0, 2, 2, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 2, 2, 2, 1, 2, 1, 1, 0,
       1, 0, 0, 2, 2, 0, 1, 1, 0, 1, 0, 2, 1, 2, 1, 1, 0, 2, 0, 1, 0, 0,
       2, 1, 1, 0, 1, 2, 0, 2, 1, 1, 2, 2, 1, 1, 0, 0, 1, 0, 0, 1, 2, 2,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 1, 1, 1, 0, 1, 2, 0, 0,
       0, 1, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 1, 2, 0, 2, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 2, 0, 0, 2, 2, 2, 1, 0, 0, 2, 0, 2, 2, 0,
       1, 2, 0, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0, 1, 1,

In [46]:
#dataframe
df = pd.DataFrame(X)
df1 = pd.DataFrame(y)

In [47]:
df

0         1         2         3         4         5         6  \
0    0.926794 -1.111157  0.824407  2.016050  0.508029 -0.547842 -0.959702   
1   -1.696593 -0.492597  1.762630 -0.596411  0.976020  0.133295 -0.881442   
2   -0.407594 -0.194870  0.424278 -0.699878  0.676409 -1.763870  0.817000   
3    0.442116 -0.208885  0.146251 -0.053855  0.015567 -0.581498  0.938416   
4    0.649734  1.447001  0.849292 -0.523628 -0.958489  0.250357  0.306469   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.652417 -1.341164 -1.482856  1.913044 -0.665875 -0.816755 -0.934185   
996  1.665106 -0.809423 -0.872130  2.834013 -0.646823  0.617608 -1.619306   
997  1.607929 -0.796752 -0.031822  2.750856  0.572372  0.473759 -1.572058   
998  2.298120 -0.445846 -1.657637  3.360958 -1.477617  0.340466 -1.997031   
999  0.570301 -1.768148  0.933659  2.249712 -0.084871  0.753100 -1.179317   

            7         8         9  
0   -0.799540 -1.074763 -0.943902  
1   -0.223451 -0.489259  2.036076  
2    0.160027  0.421380 -0.587907  
3    1.752356 -1.233754 -1.529001  
4    0.222508 -0.259538  0.384780  
..        ...       ...       ...  
995 -0.317245 -2.549519 -0.914805  
996  1.152829  1.986500 -0.728986  
997  1.866228 -0.000353 -0.709396  
998 -0.296029 -0.903851 -0.634236  
999 -0.481403 -0.721239 -0.981177  

[1000 rows x 10 columns]

In [51]:
df1.value_counts()

0
2    336
1    334
0    330
Name: count, dtype: int64

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [54]:
X_train.shape,X_test.shape

((700, 10), (300, 10))

In [63]:
#model
from sklearn.linear_model import LogisticRegression
regression =LogisticRegression(multi_class='ovr')
regression

LogisticRegression(multi_class='ovr')

In [64]:
regression.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [65]:
y_pred = regression.predict(X_test)
y_pred

array([1, 2, 1, 1, 0, 2, 2, 2, 1, 1, 0, 0, 1, 0, 0, 2, 0, 1, 2, 0, 2, 1,
       0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 0, 1, 2, 2, 1, 1, 0, 0, 1, 1, 2,
       1, 2, 1, 0, 0, 1, 2, 1, 0, 0, 2, 0, 2, 1, 0, 0, 1, 0, 1, 1, 2, 1,
       0, 2, 0, 1, 0, 1, 2, 1, 0, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 1, 1, 1, 1, 1, 2, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 1, 1, 2,
       0, 2, 0, 2, 1, 0, 0, 1, 0, 1, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0,
       1, 1, 1, 1, 1, 0, 1, 2, 0, 0, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2,
       1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 2, 0, 2, 1, 1, 1,
       2, 0, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 0,
       1, 2, 1, 0, 1, 0, 1, 0, 0, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 0, 2, 2,
       0, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 0, 0, 1, 2, 0, 2, 2, 0, 1, 0, 2,
       0, 1, 2, 2, 0, 1, 2, 1, 0, 2, 2, 1, 1, 0, 1, 1, 1, 2, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 2, 0, 0, 2, 1, 1, 0, 2, 1, 1, 1,
       1, 2, 0, 0, 1, 2, 1, 0, 0, 0, 0, 2, 1, 0])

In [66]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [67]:
score = accuracy_score(y_test,y_pred)
print(score)
cn=confusion_matrix(y_test,y_pred)
print(cn)
print(classification_report(y_test,y_pred))

0.7066666666666667
[[76  0 26]
 [ 9 83  8]
 [12 33 53]]
              precision    recall  f1-score   support

           0       0.78      0.75      0.76       102
           1       0.72      0.83      0.77       100
           2       0.61      0.54      0.57        98

    accuracy                           0.71       300
   macro avg       0.70      0.71      0.70       300
weighted avg       0.70      0.71      0.70       300



#Hyperparameter Tuning


#RandomizedSearch CV

In [70]:
model = LogisticRegression(multi_class='ovr')
model

LogisticRegression(multi_class='ovr')

In [71]:
penalty = ['l1','l2','elasticnet']
c_values = [100,10,1.0,0.1,0.01]
solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

In [73]:
params = dict(penalty=penalty,C = c_values,solver=solver)
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['lbfgs',
  'liblinear',
  'newton-cg',
  'newton-cholesky',
  'sag',
  'saga']}

In [78]:
from sklearn.model_selection import RandomizedSearchCV
random = RandomizedSearchCV(estimator=model,param_distributions=params,scoring='accuracy',cv=5)

In [79]:
random.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was depre

RandomizedSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [80]:
random

RandomizedSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [81]:
random.best_score_

0.7471428571428571

In [83]:
random.best_params_

{'solver': 'newton-cholesky', 'penalty': 'l2', 'C': 0.1}

In [84]:
random.predict(X_test)

array([1, 2, 1, 1, 0, 2, 2, 2, 1, 1, 0, 0, 1, 0, 0, 2, 0, 1, 2, 0, 2, 1,
       0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 0, 1, 2, 2, 1, 1, 0, 0, 1, 1, 2,
       1, 2, 1, 0, 0, 1, 2, 1, 0, 0, 2, 0, 2, 1, 0, 0, 1, 0, 1, 1, 2, 1,
       0, 2, 0, 1, 0, 1, 2, 1, 0, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 0,
       2, 0, 2, 1, 1, 1, 1, 1, 2, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 1, 1, 2,
       0, 2, 0, 2, 1, 0, 0, 1, 0, 1, 2, 1, 0, 2, 0, 1, 0, 2, 1, 1, 2, 0,
       1, 2, 1, 1, 1, 0, 1, 2, 0, 0, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2,
       1, 2, 1, 2, 1, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 2, 0, 2, 1, 1, 1,
       2, 0, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 0,
       1, 2, 1, 0, 1, 0, 1, 0, 0, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 0, 2, 2,
       0, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 0, 0, 1, 2, 2, 2, 2, 0, 1, 0, 2,
       0, 1, 2, 2, 0, 1, 2, 1, 0, 2, 2, 1, 1, 0, 1, 1, 1, 2, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 2, 0, 0, 2, 1, 1, 0, 2, 1, 1, 1,
       1, 1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 2, 1, 0])

In [85]:
score = accuracy_score(y_test,y_pred)
print(score)
cn=confusion_matrix(y_test,y_pred)
print(cn)
print(classification_report(y_test,y_pred))

0.7066666666666667
[[76  0 26]
 [ 9 83  8]
 [12 33 53]]
              precision    recall  f1-score   support

           0       0.78      0.75      0.76       102
           1       0.72      0.83      0.77       100
           2       0.61      0.54      0.57        98

    accuracy                           0.71       300
   macro avg       0.70      0.71      0.70       300
weighted avg       0.70      0.71      0.70       300

